import type { CSSProperties } from "react";

export const s = {
  section: { display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,
  lead: { fontSize: 12.5, color: "var(--text-muted)", lineHeight: 1.55 } satisfies CSSProperties,
  pickRow: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  pickedName: {
    fontSize: 12.5,
    color: "var(--text-secondary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  divider: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 11,
    color: "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  } satisfies CSSProperties,
  rule: { flex: 1, height: 1, background: "var(--border)" } satisfies CSSProperties,
  error: {
    display: "flex",
    gap: 9,
    alignItems: "flex-start",
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--crit)",
    background: "var(--crit-bg)",
    fontSize: 12.5,
    color: "var(--text-secondary)",
    lineHeight: 1.5,
  } satisfies CSSProperties,

  // ---- preview step ----
  ignoredBox: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-surface)",
    padding: "12px 14px",
    marginTop: 16,
  } satisfies CSSProperties,
  ignoredTitle: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    fontSize: 12.5,
    fontWeight: 600,
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  ignoredHint: {
    fontSize: 11.5,
    color: "var(--text-muted)",
    margin: "4px 0 9px",
    lineHeight: 1.5,
  } satisfies CSSProperties,
  ignoredList: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    margin: 0,
    padding: 0,
    listStyle: "none",
  } satisfies CSSProperties,
  ignoredItem: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    fontSize: 11.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  warnings: {
    display: "flex",
    flexDirection: "column",
    gap: 5,
    marginTop: 14,
  } satisfies CSSProperties,
  warning: {
    display: "flex",
    alignItems: "flex-start",
    gap: 7,
    fontSize: 11.5,
    color: "var(--text-muted)",
    lineHeight: 1.45,
  } satisfies CSSProperties,
  footerNote: {
    fontSize: 11.5,
    color: "var(--text-muted)",
    marginRight: "auto",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
  } satisfies CSSProperties,
  footer: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
} as const;
