import type { CSSProperties } from "react";

export const s = {
  wrap: { maxWidth: 900 } satisfies CSSProperties,
  h2: { fontSize: 16, fontWeight: 700 } satisfies CSSProperties,
  lead: { fontSize: 12.5, color: "var(--text-muted)", margin: "4px 0 10px" } satisfies CSSProperties,
  attribution: {
    display: "flex",
    gap: 8,
    alignItems: "flex-start",
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    fontSize: 12,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    marginBottom: 18,
  } satisfies CSSProperties,
  error: { fontSize: 13, color: "var(--crit)" } satisfies CSSProperties,

  tiles: { display: "flex", gap: 12, marginBottom: 20 } satisfies CSSProperties,
  tile: {
    flex: 1,
    padding: 15,
    borderRadius: 9,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  tileHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 32,
  } satisfies CSSProperties,
  tileLabel: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--text-muted)",
    letterSpacing: "0.03em",
    textTransform: "uppercase",
  } satisfies CSSProperties,
  tileValue: {
    marginTop: 8,
    fontSize: 26,
    fontWeight: 700,
    letterSpacing: "-0.02em",
  } satisfies CSSProperties,
  tileSuffix: { fontSize: 15, color: "var(--text-muted)" } satisfies CSSProperties,
  tileNote: { marginTop: 4, fontSize: 11.5, color: "var(--text-muted)" } satisfies CSSProperties,

  cards: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16 } satisfies CSSProperties,
  agentList: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  agentRow: {
    display: "flex",
    alignItems: "center",
    gap: 9,
    padding: "8px 10px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  agentIcon: {
    width: 22,
    height: 22,
    borderRadius: 6,
    background: "var(--accent-bg)",
    color: "var(--accent)",
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
  } satisfies CSSProperties,
  agentName: { fontSize: 12.5, fontWeight: 600, flex: 1 } satisfies CSSProperties,
  disabled: {
    fontSize: 11,
    color: "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  } satisfies CSSProperties,
  bars: { marginTop: 4 } satisfies CSSProperties,
  noFindings: { fontSize: 12.5, color: "var(--text-muted)", marginTop: 8 } satisfies CSSProperties,
} as const;
