import type { CiExportInput } from '@devdigest/shared';
import { AppError } from '../../platform/errors.js';
import {
  ACTION_CHECKOUT,
  ACTION_SETUP_NODE,
  ACTION_UPLOAD_ARTIFACT,
  CI_TRIGGERS,
  RESULT_ARTIFACT_FILE,
  RUNNER_ENTRY,
  RUNNER_NODE_VERSION,
} from './constants.js';

/**
 * The GitHub Actions workflow written into the TARGET repository.
 *
 * Written as text rather than assembled and `yaml.stringify`d, because this file
 * is READ — by the reviewer of the pull request we open, who is being asked to
 * approve a `permissions` block and three third-party actions. Comments and line
 * order are part of what they approve, and a serializer keeps neither.
 *
 * The security shape, all of it deliberate:
 *   - `pull_request`, never `pull_request_target`. The latter runs trusted code
 *     with secrets against a fork's untrusted input; it is the standard way this
 *     kind of workflow is exploited.
 *   - a job-level `if` that additionally refuses fork pull requests outright, so
 *     the job is skipped rather than failing late with no token.
 *   - every `uses:` pinned to a commit SHA. A tag is mutable.
 *   - no `github.event.*` value interpolated into any `run:` line — every one of
 *     them arrives through `env:`, where a PR title full of shell metacharacters
 *     is data instead of code.
 */
export interface WorkflowInput {
  /** `pull_request` activity types; must be members of `CI_TRIGGERS`. */
  triggers: readonly string[];
  /** How the runner publishes its review. */
  postAs: CiExportInput['post_as'];
}

export function buildWorkflowYaml(input: WorkflowInput): string {
  const triggers = normalizeTriggers(input.triggers);

  return `# Generated by DevDigest. Do not edit by hand — re-run "Export to CI" in the
# studio to regenerate it. The review itself runs from \`${RUNNER_ENTRY}\`,
# a self-contained bundle committed alongside this file.
name: DevDigest review

on:
  pull_request:
    types: [${triggers.join(', ')}]

# Exactly what the runner needs: read the code, write a review. Nothing here can
# push a commit or change a setting.
permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    name: DevDigest review
    runs-on: ubuntu-latest
    # Skip pull requests from forks. On the \`pull_request\` event a fork PR gets a
    # read-only token and no secrets, so the job could only fail. The event that
    # WOULD give it both runs this repository's code against a fork's input, and
    # is deliberately not used here.
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Check out the pull request head
        uses: ${ACTION_CHECKOUT}
        with:
          ref: \${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set up Node
        uses: ${ACTION_SETUP_NODE}
        with:
          node-version: '${RUNNER_NODE_VERSION}'

      - name: Review the pull request
        id: review
        env:
          OPENROUTER_API_KEY: \${{ secrets.OPENROUTER_API_KEY }}
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
          DEVDIGEST_POST_AS: ${input.postAs}
          PR_NUMBER: \${{ github.event.pull_request.number }}
        # The exit code is captured before it is re-raised, so the reporting step
        # below can send it on while the job still goes red on a blocking finding.
        run: |
          node ${RUNNER_ENTRY} || code=\$?
          code=\${code:-0}
          echo "exit_code=\$code" >> "\$GITHUB_OUTPUT"
          exit "\$code"

      # \`always()\` and not \`failure()\`: the artifact is the record of the review,
      # and a review that found nothing is exactly as worth keeping as one that
      # failed the gate.
      - name: Upload the review result
        if: always()
        uses: ${ACTION_UPLOAD_ARTIFACT}
        with:
          name: devdigest-result
          path: ${RESULT_ARTIFACT_FILE}
          if-no-files-found: ignore

      # Optional: only runs when the studio is reachable from CI. The condition
      # reads \`env\`, not \`secrets\` — the \`secrets\` context is not available in an
      # \`if:\` — and \`continue-on-error\` keeps a reporting failure from ever
      # reddening a review that succeeded.
      - name: Report the result to DevDigest
        if: always() && env.INGEST_URL != ''
        continue-on-error: true
        env:
          INGEST_URL: \${{ secrets.DEVDIGEST_INGEST_URL }}
          INGEST_TOKEN: \${{ secrets.DEVDIGEST_CI_TOKEN }}
          REPO: \${{ github.repository }}
          PR_NUMBER: \${{ github.event.pull_request.number }}
          COMMIT_SHA: \${{ github.event.pull_request.head.sha }}
          RUN_URL: \${{ github.server_url }}/\${{ github.repository }}/actions/runs/\${{ github.run_id }}
          EXIT_CODE: \${{ steps.review.outputs.exit_code }}
        run: |
          test -f ${RESULT_ARTIFACT_FILE} || exit 0
          jq -n \\
            --arg repo "\$REPO" \\
            --argjson pr_number "\$PR_NUMBER" \\
            --arg commit_sha "\$COMMIT_SHA" \\
            --arg run_url "\$RUN_URL" \\
            --argjson exit_code "\${EXIT_CODE:-0}" \\
            --slurpfile result ${RESULT_ARTIFACT_FILE} \\
            '{repo: \$repo, pr_number: \$pr_number, commit_sha: \$commit_sha, run_url: \$run_url, exit_code: \$exit_code, result: \$result[0]}' \\
            > devdigest-ingest.json
          curl --fail --silent --show-error --max-time 30 \\
            -X POST "\$INGEST_URL" \\
            -H "Authorization: Bearer \$INGEST_TOKEN" \\
            -H "Content-Type: application/json" \\
            --data-binary @devdigest-ingest.json
`;
}

/**
 * Keep only the activity types the wizard offers, in the canonical order, and
 * refuse anything else.
 *
 * `CiExportInput.triggers` is a bare `z.array(z.string())`, so without this an
 * arbitrary caller-supplied string would be concatenated straight into the
 * generated YAML. Ordering is canonical rather than as-given so the same
 * selection always produces a byte-identical file.
 */
function normalizeTriggers(triggers: readonly string[]): string[] {
  for (const trigger of triggers) {
    if (!(CI_TRIGGERS as readonly string[]).includes(trigger)) {
      throw new AppError(
        'ci_unknown_trigger',
        `Unknown pull_request trigger "${trigger}". Expected one of: ${CI_TRIGGERS.join(', ')}.`,
        400,
      );
    }
  }
  const selected = CI_TRIGGERS.filter((t) => triggers.includes(t));
  if (selected.length === 0) {
    throw new AppError('ci_no_trigger', 'Pick at least one pull_request trigger.', 400);
  }
  return [...selected];
}
