#!/usr/bin/env bash
#
# The deterministic half of PR self-review — the only source of auto-CRITICAL.
#
#   scripts/pr-self-review-checks.sh [base-ref]     # prints a JSON findings array
#
# Every check here is mechanical: it reads the diff, applies a rule that has a
# written owner in this repo, and cannot hallucinate. Judgement calls belong to
# the skill's LLM lanes and top out at WARNING there. The split matters because
# only what this file emits can block `gh pr create`.
#
# Two rules govern anything added here:
#
#   1. A check without a test is a false blocker waiting to happen. Prove it by
#      planting a violation and watching it fire — see scripts/test-pr-self-review.sh
#      and the 2026-08-05 depcruise entry in INSIGHTS.md.
#   2. If a rule has an open-ended exception list, it is a WARNING, not a
#      CRITICAL. Check 11 is the worked example.
#
# Output is a JSON array using the field names of the `Finding` contract
# (server/src/vendor/shared/contracts/findings.ts), so the skill can merge these
# with LLM findings without translating anything.
#
# Always exits 0 when it ran. A non-zero exit means the script itself broke, and
# callers must treat that as "not verified", never as "clean".

set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

BASE_SHA="$("$ROOT/scripts/pr-self-review-hash.sh" --print-base "${1:-}")" || {
  echo "pr-self-review-checks: cannot resolve base" >&2
  exit 1
}

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
FINDINGS="$TMP/findings.tsv"
: > "$FINDINGS"

# ---------------------------------------------------------------- helpers ----

# emit <severity> <category> <title> <file> <start> <end> <rationale> <suggestion> <source>
# Tabs separate the fields, so no field may contain one.
emit() {
  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9" >> "$FINDINGS"
}

# Changed paths with a single-letter status. Renames report their new path;
# untracked files count as additions because that is what they will be in the PR.
CHANGED="$TMP/changed.tsv"
{
  git diff --name-status "$BASE_SHA" | awk -F'\t' '{print substr($1,1,1) "\t" $NF}'
  git ls-files --others --exclude-standard | sed 's/^/A\t/'
} > "$CHANGED" 2>/dev/null

# paths_matching <extended-regex> [status-filter]
paths_matching() {
  local re="$1" st="${2:-.}"
  awk -F'\t' -v re="$re" -v st="$st" \
    '$1 ~ "^" st "$" && $2 ~ re {print $2}' "$CHANGED"
}

# added_lines <path> -> "lineno:content" for every line this diff introduces.
# Untracked files have no diff, so every line counts as new.
added_lines() {
  local f="$1"
  if git ls-files --error-unmatch "$f" >/dev/null 2>&1; then
    git diff -U0 "$BASE_SHA" -- "$f" 2>/dev/null | awk '
      /^@@/ { if (match($0, /\+[0-9]+/)) n = substr($0, RSTART+1, RLENGTH-1); next }
      /^\+\+\+/ { next }
      /^\+/ { print n ":" substr($0, 2); n++ }
    '
  elif [[ -f "$f" ]]; then
    awk '{print NR ":" $0}' "$f"
  fi
}

# first_changed_line <path> -> a line number that is guaranteed to be in the diff,
# so every finding this file emits survives the skill's grounding gate.
first_changed_line() {
  local n
  n="$(added_lines "$1" | head -1 | cut -d: -f1)"
  [[ -n "$n" ]] && echo "$n" || echo 1
}

has_changed() { paths_matching "$1" | grep -q . ; }

# ------------------------------------------------------------- 1. vendor/ui --
# client/src/vendor/ui is a vendored design system the root CLAUDE.md marks
# do-not-touch. Locally there is no PR body to read an "explicitly requested"
# exemption out of, so any change blocks and the override is the way through.
for f in $(paths_matching '^client/src/vendor/ui/'); do
  emit CRITICAL style "Vendored design system modified" "$f" \
    "$(first_changed_line "$f")" "$(first_changed_line "$f")" \
    "client/src/vendor/ui/** is vendored and listed under 'Do not touch' in CLAUDE.md. Changes here are overwritten on the next vendor sync." \
    "Revert this file, or re-run with --override if the change was explicitly requested." \
    check:vendor-ui
done

# ----------------------------------------------------- 2. migration hand-edit --
# drizzle-kit generates these. A new file (status A) is normal; editing one that
# already shipped rewrites history other machines have already applied.
for f in $(paths_matching '^server/src/db/migrations/' 'M|D'); do
  emit CRITICAL bug "Generated migration edited by hand" "$f" \
    "$(first_changed_line "$f")" "$(first_changed_line "$f")" \
    "server/src/db/migrations/** is generated by drizzle-kit. Editing an applied migration desynchronises databases that already ran it." \
    "Revert the file and express the change as a new migration via 'pnpm db:generate'." \
    check:migration-edit
done

# -------------------------------------------------------- 3. contract mirror --
# The two vendor/shared trees are hand-synced copies and have drifted before, so
# comparing the files wholesale would light up on history. Compare only the lines
# THIS diff touches on each side.
SRV="$(git diff -U0 "$BASE_SHA" -- server/src/vendor/shared 2>/dev/null \
  | grep -E '^[+-]' | grep -vE '^(\+\+\+|---)' | sed 's/^.//' | sort)"
CLI="$(git diff -U0 "$BASE_SHA" -- client/src/vendor/shared 2>/dev/null \
  | grep -E '^[+-]' | grep -vE '^(\+\+\+|---)' | sed 's/^.//' | sort)"
if [[ -n "$SRV" && "$SRV" != "$CLI" ]]; then
  f="$(paths_matching '^server/src/vendor/shared/' | head -1)"
  emit CRITICAL bug "Contract changed without its mirror" "$f" \
    "$(first_changed_line "$f")" "$(first_changed_line "$f")" \
    "server/src/vendor/shared is the source of truth and client/src/vendor/shared is a hand-synced copy; this diff changes one side only. The client build keeps the old contract." \
    "Apply the identical edit under client/src/vendor/shared/." \
    check:contract-mirror
fi

# ------------------------------------------------- 4. schema without migration --
if has_changed '^server/src/db/schema/'; then
  if ! paths_matching '^server/src/db/migrations/.*\.sql$' 'A' | grep -q .; then
    f="$(paths_matching '^server/src/db/schema/' | head -1)"
    emit CRITICAL bug "Schema changed with no new migration" "$f" \
      "$(first_changed_line "$f")" "$(first_changed_line "$f")" \
      "A Drizzle schema file changed but the diff adds no migration. Migrations do not run on boot, so the deployed database keeps the old shape." \
      "Run 'pnpm db:generate' in server/ and commit the generated migration." \
      check:schema-migration
  fi
fi

# ---------------------------------------------------------- 5. prompt mirror --
# docs/agent-prompts/*.md and seed-prompts.ts are two hand-synced sources; the
# README beside the prompts is documentation, not a prompt.
PROMPT_DOCS="$(paths_matching '^docs/agent-prompts/.*\.md$' | grep -v 'README\.md$' | head -1)"
SEED_PROMPTS="$(paths_matching '^server/src/db/seed-prompts\.ts$' | head -1)"
if [[ -n "$PROMPT_DOCS" && -z "$SEED_PROMPTS" ]]; then
  emit CRITICAL bug "Agent prompt changed without its seed mirror" "$PROMPT_DOCS" \
    "$(first_changed_line "$PROMPT_DOCS")" "$(first_changed_line "$PROMPT_DOCS")" \
    "docs/agent-prompts/*.md and server/src/db/seed-prompts.ts are synced by hand (server/CLAUDE.md). Only the document changed, so a fresh seed still writes the old prompt." \
    "Mirror the change into server/src/db/seed-prompts.ts." \
    check:prompt-mirror
elif [[ -z "$PROMPT_DOCS" && -n "$SEED_PROMPTS" ]]; then
  emit CRITICAL bug "Seed prompt changed without its document" "$SEED_PROMPTS" \
    "$(first_changed_line "$SEED_PROMPTS")" "$(first_changed_line "$SEED_PROMPTS")" \
    "server/src/db/seed-prompts.ts changed but its reviewable original under docs/agent-prompts/ did not." \
    "Mirror the change into the matching docs/agent-prompts/*.md." \
    check:prompt-mirror
fi

# ------------------------------------------------------ 6. DB test in unit lane --
# CI splits the lanes on the *.it.test.ts glob, so a DB-backed test named plainly
# runs in the unit job, where there is no Postgres.
for f in $(paths_matching '^server/test/.*\.test\.ts$' 'A|M'); do
  case "$f" in *.it.test.ts) continue ;; esac
  hit="$(added_lines "$f" | grep -nE 'testcontainers|PostgreSqlContainer|makeTestDb|db/client' | head -1)"
  [[ -n "$hit" ]] || continue
  ln="$(echo "$hit" | sed 's/^[0-9]*://' | cut -d: -f1)"
  emit CRITICAL test "DB-backed test outside the integration lane" "$f" "$ln" "$ln" \
    "This test reaches for a real database but is not named *.it.test.ts, and CI splits its lanes on exactly that glob — it will run in the unit job, which has no Postgres." \
    "Rename to *.it.test.ts. If the unit under test genuinely needs Docker, the layering is wrong — see the onion-architecture skill." \
    check:it-test-lane
done

# ------------------------------------------------------- 7. fetch in a component --
# The character class before 'fetch' is what keeps refetch() out; there are four
# legitimate refetch() call sites in the tree today. client/src/lib is the one
# place a real fetch belongs (api.ts).
for f in $(paths_matching '^client/src/(app|components)/.*\.(ts|tsx)$'); do
  hit="$(added_lines "$f" | grep -E '(^|[^A-Za-z0-9_])fetch\(' | head -1)"
  [[ -n "$hit" ]] || continue
  ln="$(echo "$hit" | cut -d: -f1)"
  emit CRITICAL bug "fetch() called from a component" "$f" "$ln" "$ln" \
    "client/CLAUDE.md allows no fetch in components: every request goes through a TanStack Query hook in client/src/lib/hooks/. A direct fetch bypasses caching, invalidation and the ApiError contract." \
    "Add or reuse a hook in client/src/lib/hooks/ and export it from hooks/index.ts." \
    check:component-fetch
done

# -------------------------------------------------------------- 8. secrets ----
SECRET_RE='sk_live_|sk-ant-[A-Za-z0-9]|ghp_[A-Za-z0-9]{20}|github_pat_[A-Za-z0-9]{20}|AKIA[0-9A-Z]{16}|-----BEGIN [A-Z ]*PRIVATE KEY-----'
for f in $(paths_matching '.' 'A|M'); do
  case "$f" in
    *.lock|*lock.yaml|*lock.json) continue ;;
    server/clones/*) continue ;;
    # This file defines the patterns and the test file plants them on purpose;
    # scanning either is guaranteed self-detection.
    scripts/pr-self-review-checks.sh|scripts/test-pr-self-review.sh) continue ;;
  esac
  hit="$(added_lines "$f" | grep -E "$SECRET_RE" | head -1)"
  [[ -n "$hit" ]] || continue
  ln="$(echo "$hit" | cut -d: -f1)"
  emit CRITICAL security "Credential literal added to the repository" "$f" "$ln" "$ln" \
    "This line matches a live-credential pattern. Secrets never live in the repo or the database — the single read chokepoint is server/src/adapters/secrets/local.ts (~/.devdigest/secrets.json, mode 0600)." \
    "Remove the literal, move the value into ~/.devdigest/secrets.json, and rotate the credential — it is in your git history now." \
    check:secret-literal
done

# A key field on AppConfig is a design violation in itself: platform/config.ts
# has no key fields on purpose (docs/architecture.md, invariant 3).
CFG=server/src/platform/config.ts
if paths_matching '^server/src/platform/config\.ts$' | grep -q .; then
  hit="$(added_lines "$CFG" | grep -vE ':\s*(\*|//)' \
    | grep -E '(apiKey|api_key|secretKey|accessToken|password)\s*[:?]' | head -1)"
  if [[ -n "$hit" ]]; then
    ln="$(echo "$hit" | cut -d: -f1)"
    emit CRITICAL security "Credential field added to AppConfig" "$CFG" "$ln" "$ln" \
      "platform/config.ts has no key fields by design (docs/architecture.md, invariant 3). Secrets resolve through SecretsProvider, never through AppConfig." \
      "Declare the value in the secrets adapter and read it via container.secrets." \
      check:config-secret
  fi
fi

# --------------------------------------------------------- 9. the onion guard --
# One depcruise pass over server/src also polices reviewer-core's purity, because
# the cruise follows the tsconfig alias into ../reviewer-core/src.
if has_changed '^(server|reviewer-core)/'; then
  if [[ ! -x server/node_modules/.bin/depcruise ]]; then
    emit WARNING bug "Architecture guard not run" server/package.json 1 1 \
      "dependency-cruiser is not installed in server/, so layering and reviewer-core purity were NOT checked. Absence of findings here means nothing." \
      "Run 'pnpm install' in server/ and re-run the review." \
      check:arch-unavailable
  elif [[ ! -d reviewer-core/node_modules ]]; then
    # Without reviewer-core's deps the alias still resolves but its own imports do
    # not, so the graph quietly changes shape and the run goes green for the wrong
    # reason (INSIGHTS.md, 2026-08-05).
    emit WARNING bug "Architecture guard ran on an incomplete graph" server/package.json 1 1 \
      "reviewer-core/node_modules is missing, so the dependency graph is incomplete and a green arch:check here is not evidence." \
      "Run 'npm ci' in reviewer-core/, then re-run the review." \
      check:arch-incomplete
  else
    ARCH_OUT="$TMP/arch.txt"
    ( cd server && ./node_modules/.bin/depcruise src \
        --config .dependency-cruiser-onion.cjs --ignore-known --output-type err ) \
        > "$ARCH_OUT" 2>&1
    if [[ $? -ne 0 ]]; then
      # "error <rule> <from> -> <to>" is the err reporter's shape.
      while IFS= read -r line; do
        from="$(echo "$line" | awk '{print $3}')"
        rule="$(echo "$line" | awk '{print $2}')"
        [[ -n "$from" ]] || continue
        emit CRITICAL bug "Layer violation: $rule" "server/$from" \
          "$(first_changed_line "server/$from")" "$(first_changed_line "server/$from")" \
          "The onion guard rejects this import. $(echo "$line" | sed 's/\t/ /g')" \
          "See the onion-architecture skill. Never add the violation to .dependency-cruiser-known-violations.json to unblock." \
          check:arch
      done < <(grep -E '^[[:space:]]*error' "$ARCH_OUT" | head -20)
    fi
  fi
fi

# ------------------------------------------------------- 10. the debt baseline --
BASELINE=server/.dependency-cruiser-known-violations.json
if paths_matching '^server/\.dependency-cruiser-known-violations\.json$' 'M' | grep -q .; then
  add="$(git diff -U0 "$BASE_SHA" -- "$BASELINE" | grep -cE '^\+[^+]')"
  del="$(git diff -U0 "$BASE_SHA" -- "$BASELINE" | grep -cE '^-[^-]')"
  if [[ "${add:-0}" -gt "${del:-0}" ]]; then
    emit CRITICAL bug "Architecture debt list grew" "$BASELINE" \
      "$(first_changed_line "$BASELINE")" "$(first_changed_line "$BASELINE")" \
      "This file is the frozen debt list, not a quota: INSIGHTS.md says never append to it to unblock a change, and anything new must fail. The diff adds more entries than it removes." \
      "Fix the violation instead. The baseline is only ever regenerated after real violations are removed." \
      check:arch-baseline
  fi
fi

# ------------------------------------------- 11. process.env outside its home --
# WARNING, not CRITICAL, and deliberately so: the legitimate exception list is
# open-ended. Today it holds the secrets adapter (documented fallback), the seed
# and migrate entrypoints, and simple-git setting variables for its subprocesses.
# tooling.md says this one is checked by eye — this only makes it easier to see.
for f in $(paths_matching '^server/src/.*\.ts$' 'A|M'); do
  case "$f" in
    server/src/platform/config.ts|server/src/adapters/secrets/*) continue ;;
    server/src/db/seed*.ts|server/src/db/migrate.ts) continue ;;
    server/src/adapters/git/*) continue ;;
  esac
  hit="$(added_lines "$f" | grep -E 'process\.env\.' | grep -vE ':\s*(\*|//)' | head -1)"
  [[ -n "$hit" ]] || continue
  ln="$(echo "$hit" | cut -d: -f1)"
  emit WARNING style "process.env read outside platform/config.ts" "$f" "$ln" "$ln" \
    "Configuration has one read chokepoint (platform/config.ts) and secrets have another (adapters/secrets/local.ts). A direct env read here is invisible to both, and the onion guard cannot see it." \
    "Add the field to AppConfig, or resolve it through container.secrets." \
    check:env-read
done

# ------------------------------------------------- 12. e2e flows and the lock --
for f in $(paths_matching '^e2e/specs/.*\.json$' 'A|M'); do
  hit="$(added_lines "$f" | grep -E '"(chat)"|localhost:|127\.0\.0\.1|https?://[^{]' | head -1)"
  [[ -n "$hit" ]] || continue
  ln="$(echo "$hit" | cut -d: -f1)"
  emit CRITICAL test "e2e flow breaks its determinism contract" "$f" "$ln" "$ln" \
    "e2e/CLAUDE.md forbids the AI 'chat' command and hardcoded hosts: flows are data, addressed through {BASE} and deterministic locators only." \
    "Use {BASE} for the origin and a --url/--text/find locator for the step." \
    check:e2e-contract
done

if paths_matching '^skills-lock\.json$' 'M' | grep -q .; then
  for name in engineering-insights frontend-architecture onion-architecture pr-self-review; do
    git diff -U0 "$BASE_SHA" -- skills-lock.json | grep -E "^\+.*\"$name\"" -q || continue
    emit CRITICAL bug "Hand-authored skill added to the vendor lock" skills-lock.json \
      "$(first_changed_line skills-lock.json)" "$(first_changed_line skills-lock.json)" \
      "'$name' is maintained by hand in this repo. Entries in skills-lock.json are re-vendored from GitHub by hash, which silently overwrites local edits (INSIGHTS.md, 2026-08-01)." \
      "Remove the entry. Hand-authored skills stay out of the lock and are listed in .claude/skills/README.md instead." \
      check:skill-lock
  done
fi

# ------------------------------------------------------------------ output ----
jq -R -s '
  split("\n") | map(select(length > 0)) | map(split("\t")) | map({
    severity:   .[0],
    category:   .[1],
    title:      .[2],
    file:       .[3],
    start_line: (.[4] | tonumber),
    end_line:   (.[5] | tonumber),
    rationale:  .[6],
    suggestion: (if .[7] == "" then null else .[7] end),
    confidence: 1,
    source:     .[8]
  })
' < "$FINDINGS"
