import type { CSSProperties } from "react";

export const s = {
  wrap: { maxWidth: 760 } satisfies CSSProperties,
  head: { display: "flex", alignItems: "center", gap: 10, marginBottom: 4 } satisfies CSSProperties,
  h2: { fontSize: 16, fontWeight: 700 } satisfies CSSProperties,
  lead: { fontSize: 12.5, color: "var(--text-muted)", margin: "6px 0 4px" } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)", marginBottom: 16 } satisfies CSSProperties,
  error: { fontSize: 13, color: "var(--crit)" } satisfies CSSProperties,

  list: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: {
    padding: "12px 14px",
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  rowCurrent: {
    padding: "12px 14px",
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "var(--border-strong)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  rowHead: { display: "flex", alignItems: "center", gap: 12 } satisfies CSSProperties,
  tag: {
    fontSize: 12.5,
    fontWeight: 700,
    color: "var(--text-secondary)",
    background: "var(--bg-hover)",
    padding: "3px 9px",
    borderRadius: 6,
    flexShrink: 0,
  } satisfies CSSProperties,
  tagCurrent: {
    fontSize: 12.5,
    fontWeight: 700,
    color: "var(--accent-text)",
    background: "var(--accent-bg)",
    padding: "3px 9px",
    borderRadius: 6,
    flexShrink: 0,
  } satisfies CSSProperties,
  meta: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  date: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  actions: { display: "flex", gap: 6 } satisfies CSSProperties,
  body: {
    margin: "12px 0 0",
    padding: "12px 14px",
    fontSize: 12,
    lineHeight: 1.6,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    background: "var(--code-bg)",
    border: "1px solid var(--border)",
    borderRadius: 8,
    maxHeight: 320,
    overflow: "auto",
  } satisfies CSSProperties,
} as const;
