import type { SmartDiffRole } from '@devdigest/shared';

/**
 * Constants for the Smart Diff (L03).
 *
 * EVERY pattern and every threshold that decides what a file is, or how big a PR
 * has to be before splitting it is worth suggesting, lives in this file. Nothing
 * in `helpers.ts`, `service.ts` or `routes.ts` may carry a path fragment or a
 * number — the acceptance criterion is literally a grep:
 *
 *   grep -nE "package-lock|dist/|\.snap" src/modules/smart-diff/{helpers,service,routes}.ts
 *
 * The reason is not tidiness. Classification is the one part of this feature a
 * reviewer will argue with ("why is my config in wiring?"), and an argument is
 * only settleable if the whole rule set is readable in one place.
 */

/**
 * The order the groups are served in — most worth a reviewer's attention first.
 *
 * This array IS the response order: `buildGroups` iterates it, so re-ordering the
 * screen is a one-line change here rather than a sort somewhere in the client.
 */
export const ROLE_ORDER: readonly SmartDiffRole[] = ['core', 'wiring', 'boilerplate'];

/** The role an unmatched path falls through to — business logic, read closely. */
export const DEFAULT_ROLE: SmartDiffRole = 'core';

// ---- Boilerplate: generated, vendored, or mechanical -----------------------

/**
 * Lock files, by basename, matched REGARDLESS of directory.
 *
 * A monorepo has one per package and none of them are at the root, so a
 * `dir/file` rule would miss exactly the case that motivates the feature. The
 * comparison is on the lowercased basename because `Gemfile.lock` and
 * `Cargo.lock` are capitalised on disk.
 */
export const LOCK_FILE_BASENAMES: readonly string[] = [
  'package-lock.json',
  'npm-shrinkwrap.json',
  'pnpm-lock.yaml',
  'yarn.lock',
  'bun.lockb',
  'bun.lock',
  'cargo.lock',
  'poetry.lock',
  'pipfile.lock',
  'go.sum',
  'gemfile.lock',
  'composer.lock',
];

/**
 * Path SEGMENTS whose whole subtree is generated, vendored or mechanical.
 *
 * Matched as a segment, never as a substring: `vendor/` must not be found inside
 * `src/vendor-audit.ts`, and `out/` must not match `layout/`. `migrations` is here
 * on the same precedent as the rest — `modules/repo-intel/service.ts`
 * (`JUNK_PATH_PATTERNS`) already treats generated SQL as skip-worthy, and this
 * repository's own `db/migrations/**` is do-not-touch, generated by drizzle-kit.
 */
export const BOILERPLATE_DIR_SEGMENTS: readonly string[] = [
  'dist',
  'build',
  'out',
  '.next',
  'coverage',
  'vendor',
  'generated',
  '__generated__',
  '__snapshots__',
  'node_modules',
  'migrations',
];

/**
 * Directory segments that make a file a TEST.
 *
 * Tests are boilerplate here — see the spec's Decision 2. That is a deliberate
 * addition to the assignment's lock/dist/snapshot list, not a slip: a reviewer
 * reading a PR top-down wants the behaviour before its verification, and
 * `repo-intel` already classifies tests the same way.
 */
export const TEST_DIR_SEGMENTS: readonly string[] = [
  'test',
  'tests',
  '__tests__',
  '__mocks__',
  'e2e',
  'spec',
  '__fixtures__',
  'fixtures',
];

/** Basename infixes that make a file a test wherever it lives. */
export const TEST_FILE_INFIXES: readonly string[] = ['.test.', '.spec.', '.it.test.'];

/** Directory segments holding documentation. */
export const DOC_DIR_SEGMENTS: readonly string[] = ['docs', 'doc', '.changeset'];

/** Extensions that are prose, not code. */
export const DOC_EXTENSIONS: readonly string[] = ['.md', '.mdx', '.rst', '.adoc', '.txt'];

/**
 * Filename SUFFIXES that are mechanical output.
 *
 * `.d.ts` is here rather than in the wiring ladder because a declaration file is
 * emitted by the compiler far more often than it is hand-written; a hand-written
 * one loses nothing by being collapsed, since its contents are also in the source
 * it declares.
 */
export const BOILERPLATE_SUFFIXES: readonly string[] = [
  '.snap',
  '.min.js',
  '.min.css',
  '.map',
  '.d.ts',
];

// ---- Wiring: configuration and entry points --------------------------------

/**
 * Basenames that are configuration or an entry point.
 *
 * `package.json` is here and NOT in boilerplate, unlike the design mock which
 * groups it with its lock file — the written rule is "wiring = configuration",
 * and a new dependency is a thing a reviewer must see. Its lock file stays
 * boilerplate; that split is an acceptance criterion.
 *
 * `config.*` is matched as a whole basename so `src/config.ts` — wiring in the
 * design's own artboard — lands there, while `src/config-loader.ts` (real logic)
 * does not.
 */
export const WIRING_BASENAMES: readonly string[] = [
  'package.json',
  'dockerfile',
  'makefile',
  'procfile',
];

/** Basename STEMS (the part before the first dot) that are configuration. */
export const WIRING_STEMS: readonly string[] = [
  'tsconfig',
  'jsconfig',
  'config',
  'index',
  'server',
  'app',
  'main',
  'docker-compose',
  'compose',
];

/**
 * Substrings that mark a configuration file wherever it sits.
 *
 * `.config.` covers `vite.config.ts`, `vitest.config.mts`, `drizzle.config.ts`;
 * `.env` covers `.env`, `.env.example`, `.env.local`; `.github/` and `.gitlab/`
 * cover CI definitions, which are wiring in the only sense that matters — they
 * change how the thing is built and run.
 */
export const WIRING_PATH_INFIXES: readonly string[] = [
  '.config.',
  '.env',
  '.github/',
  '.gitlab/',
  '.circleci/',
];

/** File extensions that are configuration data rather than code. */
export const WIRING_EXTENSIONS: readonly string[] = [
  '.yml',
  '.yaml',
  '.toml',
  '.ini',
  '.cfg',
  '.conf',
];

// ---- Split suggestion ------------------------------------------------------

/**
 * The size at which a PR is worth splitting, in changed lines (additions +
 * deletions) across every file, boilerplate included.
 *
 * 400 rather than a rounder 300: the design's own demo PR is 285 lines and its
 * banner is hidden, so the threshold has to sit above it or the mock would be
 * contradicting itself. Lock-file churn is counted because a reviewer feels it —
 * the banner is about the size of the thing in front of them, and
 * `proposed_splits` never proposes moving a lock file anyway.
 */
export const SPLIT_MIN_TOTAL_LINES = 400;

/**
 * How many areas must qualify before the banner appears.
 *
 * Two, so the banner can never suggest splitting a PR into one PR — a
 * single-proposal banner is advice that cannot be taken.
 */
export const SPLIT_MIN_PROPOSALS = 2;

/** At most this many proposals are shown; the rest would be a second PR list. */
export const SPLIT_MAX_PROPOSALS = 5;

/**
 * How many leading path segments name an "area": `src/api/public/webhooks.ts` →
 * `src/api`. One segment collapses a whole repository into `src`; three splits
 * siblings that always move together.
 */
export const SPLIT_AREA_DEPTH = 2;

/** An area with fewer files than this is not a PR of its own. */
export const SPLIT_MIN_AREA_FILES = 2;
